ALTER TABLE "lid_mappings"
  ADD COLUMN IF NOT EXISTS "full_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "first_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "business_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "push_name" VARCHAR(200),
  ADD COLUMN IF NOT EXISTS "is_my_contact" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "is_business" BOOLEAN DEFAULT false;
